package bg.softuni.timeforschool.model.enums;

public enum SchoolProfileEnum {
    CULTURE_AND_SPORT,
    ENGLISH_LANGUAGE,
    SPANISH_LANGUAGE,
    GERMAN_LANGUAGE,
    FRENCH_LANGUAGE,
    OTHER_LANGUAGE,
    NATURAL_SCIENCE,
    MATHEMATICS,
    HUMANITIES,
    SOCIAL_SCIENCE,
    SOFTWARE_AND_HARDWARE_SCIENCES,
    BUSINESS,
    ECONOMICS,
    ART,
    MUSIC,
    PROFESSIONAL_MID_SCHOOLS,
    GENERAL_EDUCATION,
    OTHERS;

}
